import {
  Project,
  GenerationJob,
  VideoTemplate,
  BrandKitItem,
  ReferenceAsset,
  UserSubscription
} from '../types';

export const SAMPLE_ASSETS: ReferenceAsset[] = [
  {
    id: 'asset-1',
    type: 'house',
    name: 'Villa Santorini Residence',
    description: 'Modern white concrete villa with cantilevered balconies, infinity edge pool, and minimalist glass façade.',
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-20',
    tags: ['Real Estate', 'Luxury', 'Minimalist'],
  },
  {
    id: 'asset-2',
    type: 'environment',
    name: 'Nordic Forest Modern Living Room',
    description: 'Double height floor-to-ceiling glass looking out at misty pine trees, warm oak timber, modular velvet seating.',
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-22',
    tags: ['Interior', 'Scandinavian', 'Warm Light'],
  },
  {
    id: 'asset-3',
    type: 'product',
    name: 'Chronograph Obsidian Watch',
    description: 'Luxury matte black titanium timepiece with sapphire crystal face and subtle luminous indices.',
    imageUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-24',
    tags: ['Product', 'Commercial', 'Studio'],
  },
  {
    id: 'asset-4',
    type: 'character',
    name: 'Protagonist - Elena Vance',
    description: 'Late 20s architect with structured navy overcoat, natural styling, consistent facial geometry and expressions.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-25',
    tags: ['Character Lock', 'Cinematic', 'Persona'],
  },
];

export const SAMPLE_TEMPLATES: VideoTemplate[] = [
  {
    id: 'tpl-1',
    title: 'Luxury Real Estate Showcase',
    category: 'Real Estate',
    description: 'High-end architectural cinematic tour with slow push-ins, drone reveals, and warm ambient sunlight.',
    duration: '30s (6 shots)',
    aspectRatio: '16:9',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-with-living-room-and-kitchen-41221-large.mp4',
    defaultPrompt: 'Architectural slow glide through luxury residence, preserving original walls and furniture with soft cinematic lighting.',
    cameraPreset: 'Dolly In',
    shotsCount: 6,
    tags: ['Architecture', 'Luxury', '4K Master'],
  },
  {
    id: 'tpl-2',
    title: 'Airbnb Professional Tour',
    category: 'Airbnb',
    description: 'True-to-life welcoming walkthrough showing authentic spaces, zero hallucination, clean natural colors.',
    duration: '24s (5 shots)',
    aspectRatio: '16:9',
    thumbnailUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-luxury-home-with-swimming-pool-and-deck-41219-large.mp4',
    defaultPrompt: 'Authentic photorealistic tour of cozy Airbnb property with realistic textures and steady camera movement.',
    cameraPreset: 'Pan Right',
    shotsCount: 5,
    tags: ['Airbnb', 'Hospitality', 'Photorealistic'],
  },
  {
    id: 'tpl-3',
    title: 'Automotive Cinematic Commercial',
    category: 'Automotive',
    description: 'Dynamic low-angle tracking shot of sports vehicle during sunset with realistic specular highlights.',
    duration: '15s (3 shots)',
    aspectRatio: '16:9',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-black-sports-car-parked-at-sunset-41710-large.mp4',
    defaultPrompt: 'High speed tracking shot of sleek sports car on coastal highway, golden hour reflections, 24fps motion blur.',
    cameraPreset: 'Tracking Shot',
    shotsCount: 3,
    tags: ['Car Ad', 'Action', 'Cinematic'],
  },
  {
    id: 'tpl-4',
    title: 'Premium Product Hero Ad',
    category: 'Product',
    description: 'Studio macro lighting reveal with micro-particle depth of field and controlled 360 orbit.',
    duration: '12s (2 shots)',
    aspectRatio: '1:1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80',
    videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-slow-motion-of-a-watch-on-a-black-background-40763-large.mp4',
    defaultPrompt: 'High-end studio product reveal on black glass, slow circular orbit with soft diffused rim lighting.',
    cameraPreset: 'Orbit Right',
    shotsCount: 2,
    tags: ['E-Commerce', 'Studio', 'Macro'],
  },
  {
    id: 'tpl-5',
    title: 'Instagram & TikTok Viral Hook',
    category: 'Social Media',
    description: 'Fast-paced vertical 9:16 cinematic transition designed for maximum watch time and visual retention.',
    duration: '10s (2 shots)',
    aspectRatio: '9:16',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
    videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-posing-for-a-photoshoot-42646-large.mp4',
    defaultPrompt: 'Fast dynamic zoom into vertical fashion portrait, neon rim light, smooth stabilized motion.',
    cameraPreset: 'Dolly In',
    shotsCount: 2,
    tags: ['Reels', 'TikTok', 'Vertical 9:16'],
  },
  {
    id: 'tpl-6',
    title: 'Epic Drone Landscape Flyover',
    category: 'Travel',
    description: 'Sweeping wide-angle aerial shot over crystal coastlines and dramatic mountain ranges.',
    duration: '20s (4 shots)',
    aspectRatio: '21:9',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    videoPreviewUrl: 'https://assets.mixkit.co/videos/preview/mixkit-top-aerial-shot-of-the-sea-waves-41584-large.mp4',
    defaultPrompt: 'Expansive anamorphic drone flyover above crashing turquoise ocean waves and dramatic cliffs.',
    cameraPreset: 'Drone',
    shotsCount: 4,
    tags: ['Travel', 'Drone', '21:9 Cinema'],
  },
];

export const INITIAL_GENERATIONS: GenerationJob[] = [
  {
    id: 'gen-001',
    createdAt: '2026-08-27T18:40:00.000Z',
    status: 'Completed',
    progress: 100,
    statusMessage: 'Renderização master concluída',
    params: {
      prompt: 'Villa Horizon luxury architectural tour, living room with open pool terrace and panoramic mountain vista, 35mm lens, golden hour rays.',
      enhancedPrompt: '8k photorealistic architectural film, ARRI Alexa 65, 35mm Master Prime, slow steady push-in towards panoramic double-height sliding glass opening to infinite pool terrace, authentic marble reflections, warm afternoon sunlight, 24fps cinema cadence.',
      negativePrompt: 'warping, flickering, distorted architecture, floating furniture, plastic look, oversaturation',
      mode: 'image-to-video',
      provider: 'google-veo',
      modelTier: 'quality',
      aspectRatio: '16:9',
      resolution: '4K',
      isNativeResolution: false,
      fps: 24,
      quality: 'Cinema',
      durationSeconds: 6,
      camera: {
        movement: 'Dolly In',
        speed: 'Slow',
        stability: 'Smooth',
        lens: '35mm',
        depthOfField: 'Medium',
        zoomLevel: 1.0,
        focusDistance: 'Subject',
        cameraHeight: 'Eye level',
        fov: 65,
      },
      motion: {
        strength: 35,
        subjectMotion: 20,
        cameraMotion: 40,
        environmentMotion: 30,
      },
      realismStyle: 'Photorealistic',
      realismSliders: {
        realism: 98,
        textureDetail: 95,
        lightingAccuracy: 96,
        motionNaturalness: 94,
        physicsAccuracy: 96,
        faceConsistency: 92,
        environmentConsistency: 98,
      },
      preserveReference: 'Maximum',
      consistency: {
        characterLock: false,
        faceLock: false,
        objectLock: true,
        environmentLock: true,
        styleLock: true,
        cameraLock: true,
      },
      audio: {
        enabled: true,
        type: 'Ambient Sound',
        prompt: 'Gentle pool water lap, distant summer breeze, warm quiet room ambiance',
        autoSync: true,
      },
      initialImageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      seed: 849204,
    },
    resultVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-with-living-room-and-kitchen-41221-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    durationActual: 6,
    renderingEngine: 'Veo 3.1 Pro Neural Pipeline',
    providerUsed: 'google-veo',
    costCredits: 8,
  },
  {
    id: 'gen-002',
    createdAt: '2026-08-27T19:15:00.000Z',
    status: 'Completed',
    progress: 100,
    statusMessage: 'Renderização master concluída',
    params: {
      prompt: 'Aerial drone orbit of luxury infinity pool overlooking coastal sunset, crystal clear water with realistic ripples.',
      enhancedPrompt: 'Cinematic drone orbit around cantilevered infinity pool at blue hour, architectural deck lighting reflecting on water, ultra-smooth stabilization, 8k textures.',
      negativePrompt: 'blurry water, jagged edges, jittery movement, low resolution',
      mode: 'text-to-video',
      provider: 'runway-gen3',
      modelTier: 'quality',
      aspectRatio: '16:9',
      resolution: '4K',
      isNativeResolution: false,
      fps: 24,
      quality: 'Cinema',
      durationSeconds: 8,
      camera: {
        movement: 'Orbit Right',
        speed: 'Slow',
        stability: 'Smooth',
        lens: '24mm',
        depthOfField: 'Deep',
        zoomLevel: 1.0,
        focusDistance: 'Subject',
        cameraHeight: 'Overhead',
        fov: 75,
      },
      motion: {
        strength: 40,
        subjectMotion: 30,
        cameraMotion: 45,
        environmentMotion: 40,
      },
      realismStyle: 'Cinematic',
      realismSliders: {
        realism: 95,
        textureDetail: 94,
        lightingAccuracy: 95,
        motionNaturalness: 96,
        physicsAccuracy: 97,
        faceConsistency: 90,
        environmentConsistency: 96,
      },
      preserveReference: 'High',
      consistency: {
        characterLock: false,
        faceLock: false,
        objectLock: true,
        environmentLock: true,
        styleLock: true,
        cameraLock: true,
      },
      audio: {
        enabled: true,
        type: 'Music',
        prompt: 'Modern luxury deep house chillout with soft piano',
        autoSync: true,
      },
      seed: 491028,
    },
    resultVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-luxury-home-with-swimming-pool-and-deck-41219-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    durationActual: 8,
    renderingEngine: 'Runway Gen-3 Cinema Alpha',
    providerUsed: 'runway-gen3',
    costCredits: 12,
  },
  {
    id: 'gen-003',
    createdAt: '2026-08-27T21:05:00.000Z',
    status: 'Completed',
    progress: 100,
    statusMessage: 'Renderização master concluída',
    params: {
      prompt: 'Night city drive with futuristic sports car, reflections of neon billboard lights on glossy black paint.',
      enhancedPrompt: 'Hyper-detailed night cinematography, anamorphic lens flares, wet asphalt reflections, smooth gimbal tracking shot of luxury vehicle.',
      negativePrompt: 'grain, pixelation, motion blur artifacts, cartoonish render',
      mode: 'text-to-video',
      provider: 'google-veo',
      modelTier: 'quality',
      aspectRatio: '16:9',
      resolution: '1080p',
      isNativeResolution: true,
      fps: 30,
      quality: 'Ultra',
      durationSeconds: 5,
      camera: {
        movement: 'Tracking Shot',
        speed: 'Normal',
        stability: 'Smooth',
        lens: '50mm',
        depthOfField: 'Shallow',
        zoomLevel: 1.0,
        focusDistance: 'Subject',
        cameraHeight: 'Low ground',
        fov: 50,
      },
      motion: {
        strength: 55,
        subjectMotion: 60,
        cameraMotion: 50,
        environmentMotion: 50,
      },
      realismStyle: 'Photorealistic',
      realismSliders: {
        realism: 92,
        textureDetail: 90,
        lightingAccuracy: 94,
        motionNaturalness: 92,
        physicsAccuracy: 94,
        faceConsistency: 88,
        environmentConsistency: 92,
      },
      preserveReference: 'High',
      consistency: {
        characterLock: false,
        faceLock: false,
        objectLock: true,
        environmentLock: true,
        styleLock: true,
        cameraLock: false,
      },
      audio: {
        enabled: true,
        type: 'Sound Effects',
        prompt: 'V8 engine rumble, turbo spool, tire tarmac sound, synth pad',
        autoSync: true,
      },
      seed: 712940,
    },
    resultVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-black-sports-car-parked-at-sunset-41710-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    durationActual: 5,
    renderingEngine: 'Veo 3.1 Pro Neural Pipeline',
    providerUsed: 'google-veo',
    costCredits: 7,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Villa Horizon — Airbnb Commercial Launch',
    description: 'Complete 30-second high-end real estate video showcase created with 6 synchronized camera angles.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-25T14:30:00.000Z',
    updatedAt: '2026-08-27T22:10:00.000Z',
    aspectRatio: '16:9',
    resolution: '4K',
    fps: 24,
    tags: ['Real Estate', 'Airbnb', '4K Master'],
    generationsCount: 8,
    status: 'active',
    tracks: [
      {
        id: 'track-video',
        name: 'Video Track 1',
        type: 'video',
        muted: false,
        locked: false,
        visible: true,
        clips: [
          {
            id: 'clip-1',
            trackId: 'track-video',
            title: 'Shot 01: Façade Reveal',
            type: 'video',
            startTime: 0,
            duration: 6,
            sourceStartTime: 0,
            sourceUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-a-luxurious-modern-house-41218-large.mp4',
            thumbnailUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
            color: '#3b82f6',
            speed: 1.0,
            volume: 100,
            transitionIn: 'fade',
          },
          {
            id: 'clip-2',
            trackId: 'track-video',
            title: 'Shot 02: Living Room Push-in',
            type: 'video',
            startTime: 6,
            duration: 6,
            sourceStartTime: 0,
            sourceUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-apartment-with-living-room-and-kitchen-41221-large.mp4',
            thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
            color: '#6366f1',
            speed: 1.0,
            volume: 100,
            transitionIn: 'crossfade',
          },
          {
            id: 'clip-3',
            trackId: 'track-video',
            title: 'Shot 03: Sunset Pool Orbit',
            type: 'video',
            startTime: 12,
            duration: 8,
            sourceStartTime: 0,
            sourceUrl: 'https://assets.mixkit.co/videos/preview/mixkit-luxury-home-with-swimming-pool-and-deck-41219-large.mp4',
            thumbnailUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
            color: '#8b5cf6',
            speed: 1.0,
            volume: 100,
            transitionIn: 'crossfade',
          },
        ],
      },
      {
        id: 'track-text',
        name: 'Titles & Overlays',
        type: 'text',
        muted: false,
        locked: false,
        visible: true,
        clips: [
          {
            id: 'clip-text-1',
            trackId: 'track-text',
            title: 'Property Title',
            type: 'text',
            startTime: 1,
            duration: 4,
            sourceStartTime: 0,
            color: '#ec4899',
            textOverlay: {
              text: 'VILLA HORIZON — SANTORINI',
              fontSize: 28,
              fontFamily: 'Plus Jakarta Sans',
              color: '#ffffff',
              position: { x: 50, y: 85 },
            },
          },
        ],
      },
      {
        id: 'track-music',
        name: 'Soundtrack',
        type: 'music',
        muted: false,
        locked: false,
        visible: true,
        clips: [
          {
            id: 'clip-audio-1',
            trackId: 'track-music',
            title: 'Ambient Luxury Piano & Chillout.wav',
            type: 'music',
            startTime: 0,
            duration: 20,
            sourceStartTime: 0,
            color: '#10b981',
            volume: 80,
          },
        ],
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'Obsidian Chrono — Global Product Campaign',
    description: '15-second high impact luxury watch commercial featuring macro lighting and liquid metal dynamics.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-26T10:00:00.000Z',
    updatedAt: '2026-08-27T16:45:00.000Z',
    aspectRatio: '1:1',
    resolution: '4K',
    fps: 30,
    tags: ['Product', 'Commercial', 'Macro'],
    generationsCount: 4,
    status: 'active',
    tracks: [],
  },
];

export const INITIAL_BRAND_KIT: BrandKitItem = {
  id: 'brand-1',
  name: 'Vision Luxury Real Estate Studio',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80',
  watermarkPosition: 'bottom-right',
  watermarkOpacity: 35,
  primaryColor: '#f59e0b',
  secondaryColor: '#3b82f6',
  fontFamily: 'Plus Jakarta Sans',
};

export const INITIAL_SUBSCRIPTION: UserSubscription = {
  plan: 'Studio',
  creditsRemaining: 4850,
  totalMonthlyCredits: 5000,
  fairUseActive: true,
  storageUsedMb: 1420,
  storageLimitMb: 50000,
  generationsThisMonth: 84,
  maxSimultaneousRenders: 6,
  features: [
    'Unlimited 4K & Enhanced 8K Export',
    'Full Multi-Track Timeline Editor',
    'Real Estate AI & Airbnb Pro Director',
    'Veo 3.1 & Runway Gen-3 Neural Engine',
    'Multi-Angle & Consistency Engine',
    'Priority Cloud GPU Allocation',
    'Unbranded Clean Commercial License',
  ],
};
